import type { Treatment } from "./public-motion-config";

type Rule = { section: string; group: RegExp; treatment: Treatment; trigger: "viewport" | "interaction" | "scroll" | "static"; reduced: "visible" };
const rule = (section: string, group: RegExp, treatment: Treatment, trigger: Rule["trigger"] = "viewport"): Rule => ({ section, group, treatment, trigger, reduced: "visible" });
const hero = (route: string) => [
  rule("hero", new RegExp(`^${route}-hero-heading\\.eyebrow$`), "identity"),
  rule("hero", new RegExp(`^${route}-hero-heading\\.(heading|description|note)$`), "text"),
  rule("hero", new RegExp(`^${route}-hero-heading\\.actions$`), "actions"),
  rule("hero", new RegExp(`^${route}\\.hero\\.art$`), "art"),
];
const cta = (route: string) => [
  rule("cta", new RegExp(`^${route}-cta-heading\\.eyebrow$`), "identity"),
  rule("cta", new RegExp(`^${route}-cta-heading\\.(heading|description|note)$`), "text"),
  rule("cta", new RegExp(`^${route}-cta-heading\\.actions$`), "actions"),
];

// Match stable semantic groups, including catalog-backed and conditional content.
export const publicMotionManifest: Record<string, readonly Rule[]> = {
  "/fitur": [...hero("fitur"), ...cta("fitur"),
    rule("feature-catalog", /^features\.(workspace|runtime|cirra|learning)\.label$/, "identity"),
    rule("features-story", /^features-story\.label$/, "identity"),
    rule("features-cirra", /^features-cirra\.label$/, "identity"),
    rule("feature-catalog", /^features\.(workspace|runtime|cirra|learning)\.heading$/, "text"),
    rule("feature-catalog", /^(virtual-laboratory|circuit-builder|interactive-wiring|code-editor|realtime-simulation|problems-debugging|ai-tutor|ai-debugger|project-assistant|learning-progress)\.identity$/, "identity"),
    rule("feature-catalog", /^(virtual-laboratory|circuit-builder|interactive-wiring|code-editor|realtime-simulation|problems-debugging|ai-tutor|ai-debugger|project-assistant|learning-progress)\.(title|description)$/, "text"),
    rule("feature-catalog", /^(virtual-laboratory|circuit-builder|interactive-wiring|code-editor|realtime-simulation|problems-debugging|ai-tutor|ai-debugger|project-assistant|learning-progress)\.details$/, "details"),
    rule("features-story", /^features-story\.(heading|description)$/, "text"),
    rule("features-story", /^features-story\.art$/, "art", "scroll"),
    rule("features-story", /^features-story\.(active|controls)$/, "control", "interaction"),
    rule("features-story", /^stage\.(Build|Wire|Code|Simulate|Debug|Learn)\.label$/, "identity"),
    rule("features-story", /^stage\.(Build|Wire|Code|Simulate|Debug|Learn)\.(title|description)$/, "text"),
    rule("features-story", /^stage\.(Build|Wire|Code|Simulate|Debug|Learn)\.art$/, "art"),
    rule("features-cirra", /^features-cirra\.(heading|description|note)$/, "text"),
    rule("features-cirra", /^features-cirra\.preview$/, "art"),
  ],
  "/belajar": [...hero("belajar"), ...cta("belajar"),
    rule("lesson-preview", /^roadmap\.(label|preview.duration)$/, "identity"),
    rule("lesson-preview", /^roadmap\.(title|description|preview.title|preview.description)$/, "text"),
    rule("lesson-preview", /^roadmap\.(art|cycle)$/, "art", "scroll"),
    rule("lesson-preview", /^roadmap\.controls$/, "control", "interaction"),
    rule("lesson-preview", /^roadmap\.preview.action$/, "actions"),
    rule("learning-structure", /^(cycle|pillars|competencies)\.label$/, "identity"),
    rule("learning-structure", /^(cycle|pillars|competencies)\.(heading|description)$/, "text"),
    rule("cycle", /^cycle\.(Learn|Build|Wire|Code|Simulate|Debug|Challenge|Evaluate)\.identity$/, "identity"),
    rule("cycle", /^cycle\.(Learn|Build|Wire|Code|Simulate|Debug|Challenge|Evaluate)\.(title|description)$/, "text"),
    rule("cycle", /^cycle\.(Learn|Build|Wire|Code|Simulate|Debug|Challenge|Evaluate)\.outcome$/, "details"),
    rule("pillars", /^principle\..+\.badge$/, "identity"),
    rule("pillars", /^principle\..+\.(title|description)$/, "text"),
    rule("competencies", /^skill\..+\.identity$/, "identity"),
    rule("competencies", /^skill\..+\.description$/, "text"),
  ],
  "/jelajahi": [...hero("jelajahi"), ...cta("jelajahi"),
    rule("concepts", /^concept\..+\.icon$/, "identity"),
    rule("concepts", /^concept\..+\.(title|description)$/, "text"),
    rule("concepts", /^concept\..+\.art$/, "art"),
    rule("capstone", /^capstone\.badges$/, "identity"),
    rule("capstone", /^capstone\.(title|description)$/, "text"),
    rule("capstone", /^capstone\.(board|sensor|output)$/, "details"),
    rule("capstone", /^capstone\.art$/, "art"),
    rule("gallery", /^gallery\.filters$/, "control", "interaction"),
    rule("gallery", /^gallery\.status$/, "text"),
    rule("gallery", /^level\.(Beginner|Intermediate|Advanced)\.title$/, "identity"),
    rule("gallery", /^level\.(Beginner|Intermediate|Advanced)\.description$/, "text"),
    rule("gallery", /^project\.[a-z-]+\.identity$/, "identity"),
    rule("gallery", /^project\.[a-z-]+\.(title|description)$/, "text"),
    rule("gallery", /^project\.[a-z-]+\.concepts$/, "details"),
    rule("gallery", /^project\.[a-z-]+\.art$/, "art"),
    rule("gallery", /^project\.[a-z-]+\.action$/, "actions"),
  ],
  "/harga": [...hero("harga"), ...cta("harga"),
    rule("plans", /^plans\.heading$/, "text"),
    rule("plans", /^plan\.(free|premium)\.identity$/, "identity"),
    rule("plans", /^plan\.(free|premium)\.(title|description)$/, "text"),
    rule("plans", /^plan\.(free|premium)\.(price|payment|feature\..+)$/, "details"),
    rule("plans", /^plan\.(free|premium)\.action$/, "actions"),
    rule("comparison", /^comparison\.label$/, "identity"),
    rule("comparison", /^comparison\.(title|description)$/, "text"),
    rule("comparison", /^comparison\..+$/, "details"),
    rule("comparison", /^access\.filters$/, "control", "interaction"),
    rule("comparison", /^access\.legend$/, "identity"),
    rule("faq", /^faq\.label$/, "identity"),
    rule("faq", /^faq\.title$/, "text"),
    rule("faq", /^faq\..+\.question$/, "control", "interaction"),
    rule("faq", /^faq\..+\.answer$/, "text"),
  ],
  "project-detail": [
    rule("detail", /^gallery\.detail\.(title|description|status)$/, "text"),
    rule("detail", /^gallery\.detail\.art$/, "art"),
    rule("detail", /^gallery\.detail\.concepts$/, "details"),
    rule("detail", /^gallery\.detail\.action$/, "actions"),
  ],
  "footer": [
    rule("footer", /^footer\.trace$/, "art"),
    rule("footer", /^footer\.logo$/, "identity"),
    rule("footer", /^footer\.description$/, "text"),
    rule("footer", /^footer\.\/(fitur|belajar|jelajahi|harga|masuk|simulator)$/, "control", "interaction"),
    rule("footer", /^footer\.copyright$/, "static", "static"),
  ],
  "controls": [rule("header", /^nav\.(logo|theme|login|simulator|menu|sheet|skip|\/(fitur|belajar|jelajahi|harga)?)$/, "control", "interaction"), rule("back-top", /^shared\.back-top$/, "control", "interaction")],
};

export function motionDefinition(route: string, group: string) {
  return publicMotionManifest[route]?.find((entry) => entry.group.test(group));
}
