import { test, expect } from "@playwright/test";

test("desktop panels resize, collapse independently, restore focus and persist", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/simulator");
  const left = page.getByTestId("left");
  const width = async () => (await left.boundingBox())!.width;
  await expect(page.getByRole("button", { name: "Toggle Parts", exact: true })).toBeEnabled();
  const center = await page.getByTestId("center").boundingBox();
  const bottom = await page.getByTestId("bottom").boundingBox();
  const sidebar = await left.boundingBox();
  expect(bottom!.x).toBeCloseTo(center!.x, 0);
  expect(bottom!.width).toBeCloseTo(center!.width, 0);
  expect(sidebar!.height).toBeCloseTo(center!.height, 0);
  const divider = page.getByRole("separator", { name: "Ubah lebar Parts" });
  await divider.focus();
  const before = await width();
  await page.keyboard.press("ArrowRight");
  await expect.poll(width).toBeGreaterThan(before);
  const handle = await divider.boundingBox();
  const pointerBefore = await width();
  await page.mouse.move(handle!.x + handle!.width / 2, handle!.y + 100);
  await page.mouse.down(); await page.mouse.move(handle!.x + 42, handle!.y + 100); await page.mouse.up();
  await expect.poll(width).toBeGreaterThan(pointerBefore);
  const rightWidth = async () => (await page.getByTestId("right").boundingBox())!.width;
  const rightBefore = await rightWidth();
  await page.getByRole("separator", { name: "Ubah lebar Properties" }).focus(); await page.keyboard.press("ArrowLeft");
  await expect.poll(rightWidth).toBeGreaterThan(rightBefore);
  await page.getByRole("button", { name: "Toggle Properties", exact: true }).click();
  await expect.poll(async () => (await page.getByTestId("right").boundingBox())!.width).toBe(0);
  const saved = await width();
  await page.getByRole("button", { name: "Focus Mode", exact: true }).click();
  await expect.poll(width).toBe(0);
  await expect.poll(async () => (await page.getByTestId("bottom").boundingBox())!.height).toBe(0);
  await page.getByRole("button", { name: "Focus Mode", exact: true }).click();
  await expect.poll(width).toBeCloseTo(saved, 0);
  await page.reload();
  await expect.poll(width).toBeCloseTo(saved, 0);
  await expect.poll(async () => (await page.getByTestId("right").boundingBox())!.width).toBe(0);
  await page.getByRole("button", { name: "Toggle Parts", exact: true }).click();
  await page.getByRole("button", { name: "Toggle Panel bawah", exact: true }).click();
  await expect.poll(width).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});

test("mobile keeps canvas and accessible sheets", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/simulator");
  await page.getByRole("button", { name: "Parts", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).not.toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});
